server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: "AutoHub User Service"
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
application:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    token-validity-in-seconds: ${JWT_VALIDITY:86400}
