server:
  port: 8080
spring:
  application:
    name: "AutoHub User Service"
  datasource:
    url: jdbc:postgresql://localhost:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    url: jdbc:postgresql://localhost:3306/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
